# TL;DR: YOU SHOULD DELETE THIS FILE
#
# This file was generated by Cucumber-Rails and is only here to get you a head start
# These step definitions are thin wrappers around the Capybara/Webrat API that lets you
# visit pages, interact with widgets and make assertions about page content.
#
# If you use these step definitions as basis for your features you will quickly end up
# with features that are:
#
# * Hard to maintain
# * Verbose to read
#
# A much better approach is to write your own higher level step definitions, following
# the advice in the following blog posts:
#
# * http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html
# * http://dannorth.net/2011/01/31/whose-domain-is-it-anyway/
# * http://elabs.se/blog/15-you-re-cuking-it-wrong
#
include Warden::Test::Helpers

require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

module WithinHelpers
  def with_scope(locator)
    locator ? within(*selector_for(locator)) { yield } : yield
  end
end
World(WithinHelpers)

Given('a user with username {string}') do |string|
  @user1 = User.create(username: string,email:"idbc@jjj.it",num_tel: "293878927")
end

Given('a challenge called {string} with no definite setted date\/time\/duration and {string} as creator') do |string,string2|
  @challenge = Challenge.create(user_id: @user1.id,description: string,durata: nil)
  JoinChallenge.create(user_id:@user1.id,challenge_id:@challenge.id)
end

Given('a user who joined the challenge called {string} with username {string}') do |string,string2|
  @user2  = User.create(username: string2,email:"idbjhbc@jjj.it",num_tel: "2938878927")
  JoinChallenge.create(user_id: @user2.id,challenge_id:@challenge.id)
end

Given('I am the user with username {string}') do |string|
  if string == "gabrinca01"
    login_as(@user1)
  else
    login_as(@user2)
  end
end

Given /^(?:|I )am in (.+)$/ do |page_name|
  visit path_to(page_name)
end

Then /^(?:|I )should be on (.+)$/ do |page_name|
  current_path = URI.parse(current_url).path
  if current_path.respond_to? :should
    current_path.should == path_to(page_name)
  else
    assert_equal path_to(page_name), current_path
  end
end

When('I fill the message form with {string}') do |string|
  fill_in('message[msg_txt]', with: string)
end

When('I click on {string}') do |string|
  click_on(string) 
end

Then('I should see the message {string} on the chat') do |string|
  page.has_content?(string)
end